- hosts: all
  sudo: True
  vars:
    db_sentry:
      name: sentry
      user: sentry
      password: redacted
    superuser_sentry:
      username: admin
      email: redacted
      password: redacted
    sentry:
      server: 1.2.3.4
      url: http://1.2.3.4
      secret_key: 'redacted'
    sentry_mail:
      host: localhost
      port: 25
      username: ''
      password: ''
      use_tls: false
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - sentry

